version: '3.1'
services:
  mysql:
    container_name: saveTrack-mysql
    image: mysql/mysql-server:8.0.27
    environment:
      - MYSQL_DATABASE=error
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1", "--max_connections=2048", "--wait_timeout=3600" ]
    ports:
      - 3306:3306
    volumes: #볼륨 지정
      - ./resources/develop-environment/mysql-init.d:/docker-entrypoint-initdb.d
    networks: #사용할 네트워크 지정
      - saveTrack

  redis:
    container_name: saveTrack-redis
    image: redis:latest
    expose:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=root
    networks:
      - saveTrack

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saveTrack-service
    ports:
      - 8080:8080
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://saveTrack-mysql:3306/saveTrack?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: root

    networks: #사용할 네트워크 지정
      - saveTrack
networks:
  saveTrack:
