name: Server CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      working-directory: ./saveTrack
      run: chmod +x ./gradlew
      shell: bash

    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

      ## gradle build
    - name: Build with Gradle
      working-directory: ./saveTrack
      run: ./gradlew build -x test

    - name: serving script in ec2 
      uses: appleboy/ssh-action@master   
      with:
        key: ${{ secrets.SERVER_EC2_SSH_KEY }}
        host: ${{ secrets.SERVER_EC2_HOST }}
        username: ${{ secrets.SERVER_EC2_USER }}
        scirpt: |
          ./script.sh
        
